version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    networks:
      - mynet
    environment: 
      - discovery.type=single-node
    volumes:
      - "$PWD/elasticseach/data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    networks: 
      - mynet
    environment: 
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
networks: 
  mynet: